// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKoY1ZsIH3IaBTwIkdYIOpa7rm8azdFLc',
    appId: '1:764473581902:web:26c56978473f386127be1f',
    messagingSenderId: '764473581902',
    projectId: 'easystudies-389209',
    authDomain: 'easystudies-389209.firebaseapp.com',
    storageBucket: 'easystudies-389209.appspot.com',
    measurementId: 'G-C7CJ20QH4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDguKEGf1yn1ST1Er_BTWbhEkS1o3CMG3Q',
    appId: '1:764473581902:android:62ca9b5125ab3c1327be1f',
    messagingSenderId: '764473581902',
    projectId: 'easystudies-389209',
    storageBucket: 'easystudies-389209.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWJ-RNVGVqZfxkgUChfMLNS-ikCIx9tkg',
    appId: '1:764473581902:ios:01a8296cccf538b227be1f',
    messagingSenderId: '764473581902',
    projectId: 'easystudies-389209',
    storageBucket: 'easystudies-389209.appspot.com',
    iosClientId: '764473581902-64u247i4g42pu9f0mta7gbhi308ebqp3.apps.googleusercontent.com',
    iosBundleId: 'com.example.applicationEasystudies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWJ-RNVGVqZfxkgUChfMLNS-ikCIx9tkg',
    appId: '1:764473581902:ios:510bc40291f38adc27be1f',
    messagingSenderId: '764473581902',
    projectId: 'easystudies-389209',
    storageBucket: 'easystudies-389209.appspot.com',
    iosClientId: '764473581902-48nspnk4s8ipvkfi87mhe3995rko7qp6.apps.googleusercontent.com',
    iosBundleId: 'com.example.applicationEasystudies.RunnerTests',
  );
}
